---
galaxy_info:
  author: rolandu
  description: >-
    Generate an SSH key for the current SSH user and export the public key to
    the controller.
  license: MIT
  min_ansible_version: 2.13
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
