galaxy_info:
  role_name: openvpn_client
  namespace: rolandu
  author: rolandu
  description: Configure an OpenVPN client from an exported .ovpn profile.
  license: MIT
  min_ansible_version: 2.13
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies: []
