---
galaxy_info:
  author: rolandu
  description: Pull certificate files from another host using rsync.
  license: MIT
  min_ansible_version: 2.13
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
