---
# Name of the client profile to install (defaults to host name)
openvpn_client_name: "{{ inventory_hostname }}"

# VPN definitions and their clients (shared with server role)
openvpn_config: []

# Local controller path for exported artifacts
artifacts_dir: "{{ inventory_dir }}/artifacts"

# Global path base for exported configs on the controller
openvpn_client_local_dir_base: "{{ artifacts_dir }}/openvpn-clients"

# Install a NetworkManager dispatcher script to auto-connect VPN when internet is available
openvpn_client_nm_autoconnect_dispatcher: true
