---
- name: Reload nginx
  block:
    - name: Validate nginx configuration before reload
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Reload nginx service
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

- name: Restart nginx
  block:
    - name: Validate nginx configuration before restart
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Restart nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
