---
galaxy_info:
  author: rolandu
  description: Install Borg and Borgmatic and render a native Borgmatic configuration.
  license: MIT
  min_ansible_version: 2.13
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
