---
galaxy_info:
  author: rolandu
  description: Set up a native WireGuard server and server-side peer keys.
  license: MIT
  min_ansible_version: 2.13
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
