---
galaxy_info:
  author: rolandu
  description: HTTPS nginx reverse proxy and static site configuration.
  license: MIT
  min_ansible_version: 2.13
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
